AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Person Table
Resources:
  person:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Type: String
        Name: id
      ProvisionedThroughput:
        WriteCapacityUnits: 5
        ReadCapacityUnits: 5
