service: sls-step-function
frameworkVersion: "2"

plugins:
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
  add:
    handler: handler.add
  double:
    handler: handler.double

stepFunctions:
  stateMachines:
    simple-maths:
      name: simple-maths
      definition:
        Comment: Simple Maths Example
        StartAt: add
        States:
          add:
            Type: Task
            Resource:
              Fn::GetAtt: [add, Arn]
            Next: double
          double:
            Type: Task
            Resource:
              Fn::GetAtt: [double, Arn]
            End: true
            Retry:
              - ErrorEquals: [NumberIsTooBig]
                MaxAttempts: 0
              - ErrorEquals: [States.ALL]
                MaxAttempts: 3
